 

version: '3'
 
services:
 
    rabbitmq:
        image: rabbitmq:3.7.5-management
        hostname: team12-rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
        environment:
            RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
            RABBITMQ_DEFAULT_USER: rabbitmq
            RABBITMQ_DEFAULT_PASS: rabbitmq
            RABBITMQ_DEFAULT_VHOST: /

